### ISSUE TITLE
Class Instance Constructor Function and Show Method

### ISSUE THREAD

**Issue by DarioS** [SydneyBioX/BenchHub#48]
Bioconductor forbids end-user usage of `new`. Also, a pretty-print `show` is required. See [Class Design](https://contributions.bioconductor.org/r-code.html?#class-design) section of Developer's Guide.

**Comment by nick-robo** [comment]
What would you change from the default print method?

```
r$> trioB1
<Trio>
  Public:
    addAuxData: function (name, auxData, metrics, args = NULL) 
    addMetric: function (name, metric, args = NULL) 
    auxData: list
    cachePath: /tmp/RtmpAfncDg
    clone: function (deep = FALSE) 
    data: tbl_df, tbl, data.frame
    dataSource: figshare
    dataSourceID: 26142922/47361046
    evaluate: function (input) 
    getAuxData: function (name) 
    getMetrics: function (auxDataName) 
    initialize: function (datasetID = NULL, cachePath = FALSE) 
    metrics: list
    split: function (y, n_fold = 5L, n_repeat = 1L, stratify = TRUE) 
    splitIndices: list
  Private:
    datasetID: NULL
    getData: function (sourceName, id, cachePath) 
    parseIDString: function (userInput) 
    populateTrio: function () 
```
